import "./tests/standings.test.mjs";
import "./tests/storage.test.mjs";
import "./tests/scoring.test.mjs";
import "./tests/ranking.test.mjs";
import "./tests/worldcup-api.test.mjs";
import "./tests/admin-prediction-options.test.mjs";
import "./tests/match-date.test.mjs";
import "./tests/share-predictions.test.mjs";
import "./tests/match-prediction-summaries.test.mjs";
